### ISSUE TITLE
As a developer, I want to add initial testing

### ISSUE THREAD

**Issue by AlexTMIT** [ITU-BDSA2024-GROUP10/Chirp#122]
Refactor the test suite from previous Chirp! CLI application.

## Acceptance Criteria: 
- [x] keeps all the test cases around that still apply to the new Razor Page application.
- [ ] adds new API tests that send GET requests to the endpoints for public and private timelines and assert that certain information is in the HTML text of the response in the HTTP body.

**Comment by stoftot** [comment]
Deprecated
