### ISSUE TITLE
As a developer i want to test the functionality of the AuthorRepository 

### ISSUE THREAD

**Issue by RasmusLarsen02** [ITU-BDSA2024-GROUP10/Chirp#162]
The functionality of the AuthorRepository should have full test coverage 

# Acceptance Criteria

- [ ] Unittest for GetAuthorByName exists & passes
- [ ] Unittest for GetAuthorByEmail exists & passes
- [ ] Unittest for CreateAuthor exists & passes

**Comment by anthoncastillo** [comment]
disregarded, replaced with more specific issues
