### ISSUE TITLE
As a developer, I want to implemented ASP.NET Core Identity

### ISSUE THREAD

**Issue by AlexTMIT** [ITU-BDSA2024-GROUP10/Chirp#215]
## Acceptance criteria:
- [x] User can register and login via ASP.NET Core Identity
- [ ] Client secrets are present in code
- [x] Passwords are hashed and stored never as clear text
- [x] #229
- [x] #230

**Comment by stoftot** [comment]
This was done in #223, we should of the adding of helge and adrian latere on, since we are properly gonna change a lot which could affect the database. Im creating a issue for it
