### ISSUE TITLE
As a developer I want to test integration of the chirp application

### ISSUE THREAD

**Issue by RasmusLarsen02** [ITU-BDSA2024-GROUP10/Chirp#24]
Add integration tests for the chirp application  

## Acceptance Criteria: 
- [ ] Test writing method works 
- [ ] Test reading method works

**Comment by anthoncastillo** [comment]
This issue has been disgarded because of the new web service features

**Comment by anthoncastillo** [comment]
This issue has been disgarded because of the new web service features
