### ISSUE TITLE
As a developer, I want to test users can read cheeps only written by those that they are following

### ISSUE THREAD

**Issue by anthoncastillo** [ITU-BDSA2024-GROUP10/Chirp#276]
This is pre-work for the new implementation of the following system. To ensure that it should behave as intended, testing beforehand is the suggested approach.

## Acceptance criteria
- [ ] playwright test for users to only see followed users' cheeps
- [ ] playwright test for user not having 'follow button' on themselves

**Comment by AlexTMIT** [comment]
Since it is mentioned in #304, it is a duplicate
