### ISSUE TITLE
As a developer, I want to make the chirp icon redirect to the public timeline

### ISSUE THREAD

**Issue by stoftot** [ITU-BDSA2024-GROUP10/Chirp#290]
## Acceptance criteria
- [x] When The icon or part of the header is clicked, the user should be redirected to the public timeline
- [x] It works whether you are signed in or not
- [x] It works on every page
- [x] The redirection takes you to page 1 of the public timeline

There is a test that,
- [x] Test if it works

**Comment by AlexTMIT** [comment]
please explain why it needs these two tests and not just one. the chirp icon is a seperate component from log in/out, right? so it should not matter?

**Comment by stoftot** [comment]
That, is a good point. The criteria have been updated accordingly.
