### ISSUE TITLE
As a user, I want to be able to register multiple accounts with the same email

### ISSUE THREAD

**Issue by AlexTMIT** [ITU-BDSA2024-GROUP10/Chirp#353]
Currently, the app does not work when one tries to do that.

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/d6db5ac9-7ac8-4664-923d-2fcd8f8ef387">

# Acceptance Criteria
- [x] User can register multiple accounts without error
- [x] User can login with both accounts

**Comment by anthoncastillo** [comment]
From personal inspection of the aforementioned bug, users are stored in the database and registered as users. However, when trying to log into the user, it will tell you that it is the wrong password. Only the original user can log into the web service. 

![{D256B364-EA8D-402B-B8C8-D4EDE4C1F5E7}](https://github.com/user-attachments/assets/95b305e7-08e5-42f2-8d34-713206dcfeec)

![{43453EAE-1A37-43B8-AE93-AD5ECF1853F4}](https://github.com/user-attachments/assets/b162f955-5eab-4aa3-9612-f0339c3ace8a)

![{D51FEAA4-5CEF-4437-B4A5-D37DA0ABFA4C}](https://github.com/user-attachments/assets/c1d6a948-b3ad-49af-9f17-3688c07da057)
